version: '2'

services:
  proxy:
    build:
      context: proxy
      dockerfile: Dockerfile
    restart: 'always'
    environment:
      NET: 'boilerplate'
    networks:
      boilerplate:
    ports:
      - '80:80'

  index:
    build:
      context: index
      dockerfile: Dockerfile
    restart: 'always'
    environment:
      NET: 'boilerplate'
    networks:
      boilerplate:
        aliases:
          - index

  cats:
    build:
      context: cats
      dockerfile: Dockerfile
    restart: 'always'
    environment:
      NET: 'boilerplate'
    networks:
      boilerplate:
        aliases:
          - cats

  dogs:
    build:
      context: dogs
      dockerfile: Dockerfile
    restart: 'always'
    environment:
      NET: 'boilerplate'
    networks:
      boilerplate:
        aliases:
          - dogs

networks:
  boilerplate:
